### PR TITLE
Add WellNode.toml

### PR DESCRIPTION
**Pull request by yarnik1**
## If this is an UPDATE for a previous genesis validator
Checks are made against your `net_address`. If this has changed since the previous testnet, make sure you provide links of previous prs merged from your previous git username.

Thanks in advance!

## Checklist before merging to `draft`
- [x] Only one toml is added in this PR
- [x] The file being added is indeed a .toml file
- [x] The toml being added is to the correct folder, and only to the correct folder
- [x] The `eth_hot_key` and `eth_cold_key` are present

### CODE REVIEW

**Comment by bengtlofgren** [comment]
This PR has been automatically closed because it does not follow the correct procedure for updating the genesis file.

**Comment by yarnik1** [comment]
> This PR has been automatically closed because it does not follow the correct procedure for updating the genesis file.

Can I add a new PR or what is the best way for me to do it?

**Comment by bengtlofgren** [comment]
This PR has been automatically closed because it does not follow the correct procedure for updating the genesis file.

**Comment by bengtlofgren** [comment]
Oh sorry, I didn't see your comment. Yes ofc please just open a new PR!

**Pull request closed without merging**
