### PR TITLE
Update oom.toml for tesntet-15

### PR DESCRIPTION
**Pull request by oom-**
# Description

All previous genesis validators should name their PRs "Update {validator_alias}.toml for tesntet-15" and provide links to previous PRs merged.

## If this is an UPDATE for a previous genesis validator

Checks are made against your `net_address`. If this has changed since the previous testnet, make sure you provide links of previous prs merged from your previous git username.

Thanks in advance!

## Checklist before merging

- [ ] Only one toml is added in this PR
- [ ] The file being added is indeed a .toml file
- [ ] The toml being added is to the correct folder, and only to the correct folder
- [ ] The `eth_hot_key` and `eth_cold_key` are present
- [ ] The `email`, `discord`, `elements` `telegram`, and `twitter` fields are present and valid

### CODE REVIEW

**Comment by s0uk4** [comment]
TOML file is not valid

TOML file is not valid

**Comment by bengtlofgren** [comment]
TOML file is not valid

**Comment by oom-** [comment]
Hey guys, what is not valid in the file ?

**Comment by oom-** [comment]
@s0uk4 or @bengtlofgren please comment this PR to approve deletion by github to completly delete this PR and the file attached with my Info.

Just write "I consent that GithubSupport remove this PR forever" thanks.

**Comment by oom-** [comment]
@s0uk4 or @bengtlofgren  ?

**Pull request closed without merging**
