### PR TITLE
Update geonodes.toml for testnet-15

### PR DESCRIPTION
**Pull request by gbuchukuri**
previous PRs 
https://github.com/anoma/namada-testnets/pull/237
https://github.com/anoma/namada-testnets/pull/1059 https://github.com/anoma/namada-testnets/pull/1474

# Description

All previous genesis validators should name their PRs "Update {validator_alias}.toml for tesntet-15" and provide links to previous PRs merged.

## If this is an UPDATE for a previous genesis validator

Checks are made against your `net_address`. If this has changed since the previous testnet, make sure you provide links of previous prs merged from your previous git username.

Thanks in advance!

## Checklist before merging

- [ ] Only one toml is added in this PR
- [ ] The file being added is indeed a .toml file
- [ ] The toml being added is to the correct folder, and only to the correct folder
- [ ] The `eth_hot_key` and `eth_cold_key` are present
- [ ] The `email`, `discord`, `elements` `telegram`, and `twitter` fields are present and valid

### CODE REVIEW

**Review by gbuchukuri — COMMENTED** [review]
edited toml

**Review by gbuchukuri — COMMENTED** [review]
update

**Review by gbuchukuri — COMMENTED** [review]
1

**Comment by bengtlofgren** [comment]
This validator was not recognised as a previous validator and has update in the title. Please read the description.

**Comment by gbuchukuri** [comment]
hello Bengt

I was genesisi validator from testnet 2 to testnet 10  , maybe you remember i did mistake when submitting PR to testnet 11  , put toml in wrong directory

**Comment by gbuchukuri** [comment]
Hello Bengt

I was genesis validator  from testnet-2 to testnet 10 , this is why I
submitted PR with "Update" ,  I resubmitted PR with "Create"  if it was not
correct , sorry

**Pull request closed without merging**
