### PR TITLE
Update Coinstamp.toml for v0.20

### PR DESCRIPTION
**Pull request by kivancbeser**
Update Coinstamp.toml for v0.20

### CODE REVIEW

**Comment by bengtlofgren** [comment]
Could not find in previous testnets

**Comment by kivancbeser** [comment]
I dont understand i participate all previous testnet version and my name is on genesis file you can check "Coinstamp"

**Comment by bengtlofgren** [comment]
You must have changed your `net_address`, as this is the first check i make.
Looking at your github history, i could not find a pr that was merged from you on our testnets.
Please help me find it otherwise.
https://github.com/kivancbeser?tab=overview&from=2022-05-01&to=2022-05-31

**Comment by kivancbeser** [comment]
https://github.com/anoma/namada-testnets/pull/188
this is my previous pr closed and merged to genesis. My machine broken so I need to change so my IP changed.

**Pull request merged**
