### PR TITLE
Add 79anvi validator

### PR DESCRIPTION
**Pull request by 79anvi**
# Description

All previous genesis validators should name their PRs "Update {validator_alias}.toml for tesntet-15" and provide links to previous PRs merged.

## If this is an UPDATE for a previous genesis validator

Checks are made against your `net_address`. If this has changed since the previous testnet, make sure you provide links of previous prs merged from your previous git username.

Thanks in advance!

## Checklist before merging

- [x] Only one toml is added in this PR
- [x] The file being added is indeed a .toml file
- [x] The toml being added is to the correct folder, and only to the correct folder
- [x] The `eth_hot_key` and `eth_cold_key` are present
- [x] The `email`, `discord`, `elements` `telegram`, and `twitter` fields are present and valid

### CODE REVIEW

**Comment by 79anvi** [comment]
Can you check my PR? @bengtlofgren

**Comment by 79anvi** [comment]
> More than one file added
> 
> This PR has been automatically closed because it does not follow the correct procedure for updating the genesis file.

Deleted second file

**Comment by bengtlofgren** [comment]
This validator was not recognised as a previous validator and has update in the title. Please read the description.

**Comment by 79anvi** [comment]
> This validator was not recognised as a previous validator and has update in the title. Please read the description.

Really?

Why did you then merge these PRs:

https://github.com/anoma/namada-testnets/pull/2247
https://github.com/anoma/namada-testnets/pull/2152
https://github.com/anoma/namada-testnets/pull/2132

Double standards?

**Pull request closed without merging**
