### PR TITLE
Create stakr-space.toml

### PR DESCRIPTION
**Pull request by papanomad535**

### CODE REVIEW

**Comment by bengtlofgren** [comment]
Can you open a new one?

**Comment by papanomad535** [comment]
reopened, create new branch or commit to main?

**Comment by bengtlofgren** [comment]
I just need you to make a new PR that only adds the new file to `public-testnet-9`. I.e go to https://github.com/anoma/namada-testnets/tree/main/namada-public-testnet-9 and create a new pr

**Comment by papanomad535** [comment]
https://github.com/anoma/namada-testnets/pull/940

**Pull request closed without merging**
