### PR TITLE
Update cms-rare.toml

### PR DESCRIPTION
**Pull request by DaveWK**
# Description

All previous genesis validators should name their PRs "Update {validator_alias}.toml for tesntet-15" and provide links to previous PRs merged.

## If this is an UPDATE for a previous genesis validator

Checks are made against your `net_address`. If this has changed since the previous testnet, make sure you provide links of previous prs merged from your previous git username.

Thanks in advance!

## Checklist before merging

- [x] Only one toml is added in this PR
- [x] The file being added is indeed a .toml file
- [ ] The toml being added is to the correct folder, and only to the correct folder
- [ ] The `eth_hot_key` and `eth_cold_key` are present
- [ ] The `email`, `discord`, `elements` `telegram`, and `twitter` fields are present and valid

### CODE REVIEW

**Comment by bengtlofgren** [comment]
Successfully validated transactions.toml file for commit hash [8c390c2](https://github.com/anoma/namada-testnets/pull/3014/commits/8c390c2d13372a2d4aa0880f72d99ea671e39cec)

**Comment by bengtlofgren** [comment]
Actually this is a lie, it does not comply with the correct metadata formulation. Please see the example PR in the docs.

**Comment by DaveWK** [comment]
@bengtlofgren 
Can you give a bit more detail? The docs were not clear about this matter. I used version `0.28.0` as directed, but
`namadac utils init-genesis-validator`
has a flag for:
`--discord-handle`
and no flag for `elements` or `twitter` so I added them manually... Is it supposed to be `discord` and not `discord_handle`? this is what the binary set in the toml...

**Comment by bengtlofgren** [comment]
Successfully validated transactions.toml file for commit hash [61032a6](https://github.com/anoma/namada-testnets/pull/3014/commits/61032a6bfbf52304be733411cf8b16060e46736f)

**Comment by bengtlofgren** [comment]
Uh oh, you've just made me aware of something quite important thank you. I didn't realise that all those fields had now become part of the cli.

**Comment by DaveWK** [comment]
OK, I put it back to `discord_handle` as per the instructions in discord

**Comment by bengtlofgren** [comment]
Successfully validated transactions.toml file for commit hash [cfdf58b](https://github.com/anoma/namada-testnets/pull/3014/commits/cfdf58b70a19464823329638c5a0b7ec43358344)

**Comment by bengtlofgren** [comment]
Successfully validated transactions.toml file for commit hash [cfdf58b](https://github.com/anoma/namada-testnets/pull/3014/commits/cfdf58b70a19464823329638c5a0b7ec43358344)

**Pull request merged**
