### PR TITLE
Add amadison79 as validator

### PR DESCRIPTION
**Pull request by amadison79**

### CODE REVIEW

**Comment by amadison79** [comment]
discord : AlphaDuCentaure#7940

**Comment by adrianbrink** [comment]
Merged manually, please be ready at 17:00 UTC!

**Comment by amadison79** [comment]
Hello Adrian,
Is it possible to modify my validator.toml from my PULL Request ?
I'm a gen validator since january ...
I made a manipulation error, I no longer have my required keys...
It's too late for tomorrow's testnet but for the one after...
Thanks in advance for your answer.

**Comment by amadison79** [comment]
Hello Adrian,
Is it possible to modify my validator.toml from my PULL Request ?
I made a manipulation error, I no longer have my required keys...
It's too late for tomorrow's testnet but for the one after...
Thanks in advance for your answer.

**Pull request closed without merging**
