### PR TITLE
Create NODEJUMPER.toml

### PR DESCRIPTION
**Pull request by vbloher**
# Description

All previous genesis validators should name their PRs "Update {validator_alias}.toml for tesntet-15" and provide links to previous PRs merged.

## If this is an UPDATE for a previous genesis validator

Checks are made against your `net_address`. If this has changed since the previous testnet, make sure you provide links of previous prs merged from your previous git username.

Thanks in advance!

## Checklist before merging

- [ ] Only one toml is added in this PR
- [ ] The file being added is indeed a .toml file
- [ ] The toml being added is to the correct folder, and only to the correct folder
- [ ] The `eth_hot_key` and `eth_cold_key` are present
- [ ] The `email`, `discord`, `elements` `telegram`, and `twitter` fields are present and valid

### CODE REVIEW

**Comment by bengtlofgren** [comment]
The transactions.toml file for [62971c7](https://github.com/anoma/namada-testnets/pull/2858/commits/62971c7a2300e33bd625f8d17ae5f2e71aa1af2c) was deemed invalid with error Invalid signatures: Signatures could not be verified

**Comment by bengtlofgren** [comment]
The transactions.toml file for [62971c7](https://github.com/anoma/namada-testnets/pull/2858/commits/62971c7a2300e33bd625f8d17ae5f2e71aa1af2c) was deemed invalid with error Invalid signatures: Signatures could not be verified

**Comment by bengtlofgren** [comment]
The transactions.toml file for [989acdc](https://github.com/anoma/namada-testnets/pull/2858/commits/989acdc9010b0a8c7815c1e55a47b3fbbd93c805) was deemed invalid with error Invalid signatures: Signatures could not be verified

**Comment by bengtlofgren** [comment]
The transactions.toml file for [989acdc](https://github.com/anoma/namada-testnets/pull/2858/commits/989acdc9010b0a8c7815c1e55a47b3fbbd93c805) was deemed invalid with error Invalid signatures: Signatures could not be verified

**Comment by bengtlofgren** [comment]
The transactions.toml file for [989acdc](https://github.com/anoma/namada-testnets/pull/2858/commits/989acdc9010b0a8c7815c1e55a47b3fbbd93c805) was deemed invalid with error Invalid signatures: Signatures could not be verified

**Comment by bengtlofgren** [comment]
The transactions.toml file for [989acdc](https://github.com/anoma/namada-testnets/pull/2858/commits/989acdc9010b0a8c7815c1e55a47b3fbbd93c805) was deemed invalid with error Invalid signatures: Signatures could not be verified

**Comment by vbloher** [comment]
@bengtlofgren hi! I created a new PR with correct validator toml file [https://github.com/anoma/namada-testnets/pull/3171](#3171). Should I close this PR or update with new correct validator toml file?

**Comment by bengtlofgren** [comment]
The transactions.toml file for [989acdc](https://github.com/anoma/namada-testnets/pull/2858/commits/989acdc9010b0a8c7815c1e55a47b3fbbd93c805) was deemed invalid with error Invalid signatures: Signatures could not be verified

**Pull request closed without merging**
