### PR TITLE
Update dsrv.toml

### PR DESCRIPTION
**Pull request by heejin-github**
# Description

All previous genesis validators should name their PRs "Update {validator_alias}.toml for tesntet-15" and provide links to previous PRs merged.

## If this is an UPDATE for a previous genesis validator

Checks are made against your `net_address`. If this has changed since the previous testnet, make sure you provide links of previous prs merged from your previous git username.

Thanks in advance!

## Checklist before merging

- [ ] Only one toml is added in this PR
- [ ] The file being added is indeed a .toml file
- [ ] The toml being added is to the correct folder, and only to the correct folder
- [ ] The `eth_hot_key` and `eth_cold_key` are present
- [ ] The `email`, `discord`, `elements` `telegram`, and `twitter` fields are present and valid

### CODE REVIEW

**Comment by bengtlofgren** [comment]
The transactions.toml file for [1326fc5](https://github.com/anoma/namada-testnets/pull/2625/commits/1326fc54dc9ada365b78ae065118d3e15e78aa64) was deemed invalid

**Comment by bengtlofgren** [comment]
The transactions.toml file for [1326fc5](https://github.com/anoma/namada-testnets/pull/2625/commits/1326fc54dc9ada365b78ae065118d3e15e78aa64) was deemed invalid

**Comment by bengtlofgren** [comment]
The transactions.toml file for [1326fc5](https://github.com/anoma/namada-testnets/pull/2625/commits/1326fc54dc9ada365b78ae065118d3e15e78aa64) was deemed invalid

**Comment by bengtlofgren** [comment]
The transactions.toml file for [1326fc5](https://github.com/anoma/namada-testnets/pull/2625/commits/1326fc54dc9ada365b78ae065118d3e15e78aa64) was deemed invalid

**Comment by bengtlofgren** [comment]
Try redoing all the steps and resubmitting this pr, it seems as though we cannot verify your signatures.

**Comment by bengtlofgren** [comment]
Try doing it with only the cli, and don't add the discord, twitter, elements, or telegram. Simply use the `--discord-handle` argument in the cli

**Comment by heejin-github** [comment]
Re submit #3164

**Pull request closed without merging**
