### PR TITLE
Update SBB.toml for v0.20

### PR DESCRIPTION
**Pull request by dose933**
Just edited to testnet 11.

I participated in all previous testnets as Genesis and always launched my node on time.

IP changed to 167.235.53.127
@bengtlofgren

### CODE REVIEW

**Comment by bengtlofgren** [comment]
Next time, please link a PR that actually contains this information. I can only find your alias, but I need a commit or pull request to refer back to

**Comment by dose933** [comment]
Noted for next time, thanks

**Comment by bengtlofgren** [comment]
Can you do it now? :D

**Comment by dose933** [comment]
> Can you do it now? :D

Last PR https://github.com/anoma/namada-testnets/pull/367 and merged in every testnet since january

**Comment by bengtlofgren** [comment]
Fantastic, thank you!

**Pull request merged**
