### PR TITLE
Update Nodes.Guru.toml

### PR DESCRIPTION
**Pull request by kinrokinro**
# Description

All previous genesis validators should name their PRs "Update {validator_alias}.toml for tesntet-15" and provide links to previous PRs merged.

## If this is an UPDATE for a previous genesis validator

Checks are made against your `net_address`. If this has changed since the previous testnet, make sure you provide links of previous prs merged from your previous git username.

Thanks in advance!

## Checklist before merging

- [x] Only one toml is added in this PR
- [x] The file being added is indeed a .toml file
- [x] The toml being added is to the correct folder, and only to the correct folder
- [x] The `eth_hot_key` and `eth_cold_key` are present
- [x] The `email`, `discord`, `elements` `telegram`, and `twitter` fields are present and valid

### CODE REVIEW

**Comment by bengtlofgren** [comment]
Successfully validated transactions.toml file for commit hash [60ac46c](https://github.com/anoma/namada-testnets/pull/2668/commits/60ac46c521e4749a9b882cafafc542d0d6f5e677)

**Comment by bengtlofgren** [comment]
Change the filename to `nodesguru.toml`

**Comment by bengtlofgren** [comment]
I don't want any more "." than the ".toml"

**Comment by kinrokinro** [comment]
> I don't want any more "." than the ".toml"

Done, sorry for that

**Comment by bengtlofgren** [comment]
Successfully validated transactions.toml file for commit hash [2f34aff](https://github.com/anoma/namada-testnets/pull/2668/commits/2f34affd6b54d8a831d86b5fa77c08d229e52799)

**Pull request merged**
