### PR TITLE
Create harun.toml

### PR DESCRIPTION
**Pull request by harunbrgn**
# Description

All previous genesis validators should name their PRs "Update {validator_alias}.toml for tesntet-15" and provide links to previous PRs merged.

## If this is an UPDATE for a previous genesis validator

Checks are made against your `net_address`. If this has changed since the previous testnet, make sure you provide links of previous prs merged from your previous git username.

Thanks in advance!

## Checklist before merging

- [ ] Only one toml is added in this PR
- [ ] The file being added is indeed a .toml file
- [ ] The toml being added is to the correct folder, and only to the correct folder
- [ ] The `eth_hot_key` and `eth_cold_key` are present
- [ ] The `email`, `discord`, `elements` `telegram`, and `twitter` fields are present and valid

### CODE REVIEW

**Comment by bengtlofgren** [comment]
The transactions.toml file for [0a4316e](https://github.com/anoma/namada-testnets/pull/2786/commits/0a4316e6d05869d844246eec230b3ff5afa7e30c) was deemed invalid with error Invalid email: @harunbrgn@hotmail.com

**Comment by bengtlofgren** [comment]
The transactions.toml file for [0a4316e](https://github.com/anoma/namada-testnets/pull/2786/commits/0a4316e6d05869d844246eec230b3ff5afa7e30c) was deemed invalid with error Invalid email: @harunbrgn@hotmail.com

**Comment by bengtlofgren** [comment]
The transactions.toml file for [0a4316e](https://github.com/anoma/namada-testnets/pull/2786/commits/0a4316e6d05869d844246eec230b3ff5afa7e30c) was deemed invalid with error Invalid email: @harunbrgn@hotmail.com

**Comment by bengtlofgren** [comment]
The transactions.toml file for [0a4316e](https://github.com/anoma/namada-testnets/pull/2786/commits/0a4316e6d05869d844246eec230b3ff5afa7e30c) was deemed invalid with error Invalid email: @harunbrgn@hotmail.com

**Comment by bengtlofgren** [comment]
The transactions.toml file for [0a4316e](https://github.com/anoma/namada-testnets/pull/2786/commits/0a4316e6d05869d844246eec230b3ff5afa7e30c) was deemed invalid with error Invalid email: @harunbrgn@hotmail.com

**Comment by bengtlofgren** [comment]
The transactions.toml file for [0a4316e](https://github.com/anoma/namada-testnets/pull/2786/commits/0a4316e6d05869d844246eec230b3ff5afa7e30c) was deemed invalid with error Invalid email: @harunbrgn@hotmail.com

**Comment by bengtlofgren** [comment]
The transactions.toml file for [0a4316e](https://github.com/anoma/namada-testnets/pull/2786/commits/0a4316e6d05869d844246eec230b3ff5afa7e30c) was deemed invalid with error Invalid email: @harunbrgn@hotmail.com

**Comment by bengtlofgren** [comment]
The transactions.toml file for [0a4316e](https://github.com/anoma/namada-testnets/pull/2786/commits/0a4316e6d05869d844246eec230b3ff5afa7e30c) was deemed invalid with error Invalid email: @harunbrgn@hotmail.com

**Comment by harunbrgn** [comment]
Hi

The email part was invalid but has now been corrected. Could you check again? Thank you
________________________________
Gönderen: Bengt Lofgren ***@***.***>
Gönderildi: 14 Aralık 2023 Perşembe 14:41
Kime: anoma/namada-testnets ***@***.***>
Bilgi: harunbrgn ***@***.***>; Author ***@***.***>
Konu: Re: [anoma/namada-testnets] Create harun.toml (PR #2786)


The transactions.toml file for 0a4316e<https://github.com/anoma/namada-testnets/pull/2786/commits/0a4316e6d05869d844246eec230b3ff5afa7e30c> was deemed invalid with error Invalid email: @***@***.******@***.***>

**Comment by bengtlofgren** [comment]
The transactions.toml file for [0a4316e](https://github.com/anoma/namada-testnets/pull/2786/commits/0a4316e6d05869d844246eec230b3ff5afa7e30c) was deemed invalid with error Invalid email: @harunbrgn@hotmail.com

**Comment by harunbrgn** [comment]
Hi

Can you please check now, I fixed the error. and I entered the information correctly.
________________________________
Gönderen: Bengt Lofgren ***@***.***>
Gönderildi: 14 Aralık 2023 Perşembe 14:59
Kime: anoma/namada-testnets ***@***.***>
Bilgi: harunbrgn ***@***.***>; Author ***@***.***>
Konu: Re: [anoma/namada-testnets] Create harun.toml (PR #2786)


The transactions.toml file for 0a4316e<https://github.com/anoma/namada-testnets/pull/2786/commits/0a4316e6d05869d844246eec230b3ff5afa7e30c> was deemed invalid with error Invalid email: @***@***.******@***.***>

**Comment by harunbrgn** [comment]
I removed the @ sign and edited it, but why am I still getting the error?

________________________________
Gönderen: Bengt Lofgren ***@***.***>
Gönderildi: 14 Aralık 2023 Perşembe 15:12
Kime: anoma/namada-testnets ***@***.***>
Bilgi: harunbrgn ***@***.***>; Author ***@***.***>
Konu: Re: [anoma/namada-testnets] Create harun.toml (PR #2786)


The transactions.toml file for 0a4316e<https://github.com/anoma/namada-testnets/pull/2786/commits/0a4316e6d05869d844246eec230b3ff5afa7e30c> was deemed invalid with error Invalid email: @***@***.******@***.***>

**Comment by bengtlofgren** [comment]
The transactions.toml file for [0a4316e](https://github.com/anoma/namada-testnets/pull/2786/commits/0a4316e6d05869d844246eec230b3ff5afa7e30c) was deemed invalid with error Invalid email: @harunbrgn@hotmail.com

**Comment by bengtlofgren** [comment]
The transactions.toml file for [a797d75](https://github.com/anoma/namada-testnets/pull/2786/commits/a797d75a04e46fc45136413a291d24d8955e249e) was deemed invalid with error Invalid signatures: Signatures could not be verified

**Comment by harunbrgn** [comment]
I really don't understand why I wasn't chosen.

________________________________
Gönderen: Bengt Lofgren ***@***.***>
Gönderildi: 14 Aralık 2023 Perşembe 15:32
Kime: anoma/namada-testnets ***@***.***>
Bilgi: harunbrgn ***@***.***>; Author ***@***.***>
Konu: Re: [anoma/namada-testnets] Create harun.toml (PR #2786)


Closed #2786<https://github.com/anoma/namada-testnets/pull/2786>.

**Pull request closed without merging**
