### PR TITLE
Create Lankou_node.toml

### PR DESCRIPTION
**Pull request by thibault-ketterer**
# Description

All previous genesis validators should name their PRs "Update {validator_alias}.toml for tesntet-15" and provide links to previous PRs merged.

## If this is an UPDATE for a previous genesis validator

Checks are made against your `net_address`. If this has changed since the previous testnet, make sure you provide links of previous prs merged from your previous git username.

Thanks in advance!

## Checklist before merging

- [x] Only one toml is added in this PR
- [x] The file being added is indeed a .toml file
- [x] The toml being added is to the correct folder, and only to the correct folder
- [x] The `eth_hot_key` and `eth_cold_key` are present
- [x] The `email`, `discord`, `elements` `telegram`, and `twitter` fields are present and valid

### CODE REVIEW

**Comment by bengtlofgren** [comment]
The transactions.toml file for [7aaee5f](https://github.com/anoma/namada-testnets/pull/2895/commits/7aaee5fba4708d915dddd06a871bd99ccc785d40) was deemed invalid with error Invalid signatures: Signatures could not be verified

**Comment by thibault-ketterer** [comment]
sorry I made a typo
please check this one instead

**Comment by bengtlofgren** [comment]
The transactions.toml file for [c3a03fc](https://github.com/anoma/namada-testnets/pull/2895/commits/c3a03fc588621b3c3fdc7fb0d1c814e176b84432) was deemed invalid with error Invalid email: thekitgmail.com

**Comment by bengtlofgren** [comment]
The transactions.toml file for [c3a03fc](https://github.com/anoma/namada-testnets/pull/2895/commits/c3a03fc588621b3c3fdc7fb0d1c814e176b84432) was deemed invalid with error Invalid email: thekitgmail.com

**Comment by bengtlofgren** [comment]
The transactions.toml file for [c3a03fc](https://github.com/anoma/namada-testnets/pull/2895/commits/c3a03fc588621b3c3fdc7fb0d1c814e176b84432) was deemed invalid with error Invalid email: thekitgmail.com

**Comment by bengtlofgren** [comment]
The transactions.toml file for [c3a03fc](https://github.com/anoma/namada-testnets/pull/2895/commits/c3a03fc588621b3c3fdc7fb0d1c814e176b84432) was deemed invalid with error Invalid email: thekitgmail.com

**Comment by bengtlofgren** [comment]
The transactions.toml file for [c3a03fc](https://github.com/anoma/namada-testnets/pull/2895/commits/c3a03fc588621b3c3fdc7fb0d1c814e176b84432) was deemed invalid with error Invalid email: thekitgmail.com

**Comment by bengtlofgren** [comment]
The transactions.toml file for [c3a03fc](https://github.com/anoma/namada-testnets/pull/2895/commits/c3a03fc588621b3c3fdc7fb0d1c814e176b84432) was deemed invalid with error Invalid email: thekitgmail.com

**Pull request closed without merging**
