### PR TITLE
Create pierreneter.toml

### PR DESCRIPTION
**Pull request by pierreneter**
# Description

All previous genesis validators should name their PRs "Update {validator_alias}.toml for tesntet-15" and provide links to previous PRs merged.

## If this is an UPDATE for a previous genesis validator

Checks are made against your `net_address`. If this has changed since the previous testnet, make sure you provide links of previous prs merged from your previous git username.

Thanks in advance!

## Checklist before merging

- [x] Only one toml is added in this PR
- [x] The file being added is indeed a .toml file
- [x] The toml being added is to the correct folder, and only to the correct folder
- [x] The `eth_hot_key` and `eth_cold_key` are present
- [x] The `email`, `discord`, `elements` `telegram`, and `twitter` fields are present and valid

### CODE REVIEW

**Comment by bengtlofgren** [comment]
The transactions.toml file for [275a42d](https://github.com/anoma/namada-testnets/pull/3150/commits/275a42dfa3ddbcabe63c64edfa36f31f56bf28a6) was deemed invalid with error Invalid email: pierreneter

**Comment by pierreneter** [comment]
fixed it, please check again, thanks @bengtlofgren

**Comment by bengtlofgren** [comment]
The transactions.toml file for [275a42d](https://github.com/anoma/namada-testnets/pull/3150/commits/275a42dfa3ddbcabe63c64edfa36f31f56bf28a6) was deemed invalid with error Invalid email: pierreneter

**Comment by bengtlofgren** [comment]
The transactions.toml file for [275a42d](https://github.com/anoma/namada-testnets/pull/3150/commits/275a42dfa3ddbcabe63c64edfa36f31f56bf28a6) was deemed invalid with error Invalid email: pierreneter

**Comment by pierreneter** [comment]
@bengtlofgren new commit in this branch is https://github.com/anoma/namada-testnets/commit/97173e8babf42f8e081f04bede01c78f7c22332b please check the file change.

**Comment by pierreneter** [comment]
https://github.com/anoma/namada-testnets/pull/3150/files

**Comment by pierreneter** [comment]
@bengtlofgren please check again

**Comment by pierreneter** [comment]
@bengtlofgren remove invalid submission

**Pull request closed without merging**
