### PR TITLE
Add snoopfear validator

### PR DESCRIPTION
**Pull request by snoopfear**

### CODE REVIEW

**Comment by snoopfear** [comment]
Hello, my name is Max, I'm an individual validator. I've been in crypto since 2017 full time. I have good tech skills and exp in linux.
twitter: @snoopfear
telegram: @snoopfear
medium: @snoopfear
reddit @snoopfear
discord: snoopfear#7031
snoopfear:matrix.org - element

I am the current Moonbeam Ambassador!
Took a part in Stake Wars NEAR and won 20k near mainnet delegation
I was able to accumulate sufficient experience and knowledge. I took part in testing: graph, solana, forta, moonbeam (ambassador), aleo, mina (Prism member), subspace, massa, minima and much more. I recently successfully passed solana testnet and am waiting for my flight to the Mainnet. Now I am an active validator of several projects in the Cosmos ecosystem - evmos, agoric, umee. I'm running a mixnode NYM. I am a member of many special tech groups in tg and discord, where we discuss the test nets together and solve the problems that have arisen. Also I’m running now: sui, starknet, ironfish, chainflip. I’m also a part of the team of like-minded people, visit pls https://synclab.team/

**Comment by snoopfear** [comment]
I've also contributed to NamadaTrustedSetup at round #2105 with the contribution hash f72cee067c3030392fb89616644b24cd2ff6e1fcbb0dfc9e0f14e7ff1ebd839ee0b74fa45306fbba60ca246aa9653f5adf02bd777cb1903d1085044196bc8929

**Review by adrianbrink — APPROVED** [review]
Status: 2

**Comment by snoopfear** [comment]
> Status: 2
can I do new pr?

**Pull request closed without merging**
