### PR TITLE
Update cuongval.toml

### PR DESCRIPTION
**Pull request by trandinncuong**
Resubmit without editing signed toml file as instruct by Bengt

### CODE REVIEW

**Comment by bengtlofgren** [comment]
Heya! Unfortunately you will have to resubmit the entire toml and resign it. The signature is made over your net address. 
So go through the entire process again and sign it again (just don't change the metadata fields this time! and also use the IP:PORT form instead of a dns like you did in this pr). Thank you!

**Comment by bengtlofgren** [comment]
@trandinncuong please confirm receipt

**Comment by trandinncuong** [comment]
Hello Bengt Lofgren,

Thank you for you informations, actually, I did follow your instruction in my last PR. However, I closed that PR and created new toml file then resubmit PR again with newly signed toml file and did not edit metadata field, please check Github

Regards
Tran Dinh Cuong








On Friday, December 15, 2023 at 04:20:38 PM GMT+7, Bengt Lofgren ***@***.***> wrote: 







Heya! Unfortunately you will have to resubmit the entire toml and resign it. The signature is made over your net address.
So go through the entire process again and sign it again (just don't change the metadata fields this time! and also use the IP:PORT form instead of a dns like you did in this pr). Thank you!

**Comment by trandinncuong** [comment]
Yes, have I did it, please check github PR






On Friday, December 15, 2023 at 04:20:38 PM GMT+7, Bengt Lofgren ***@***.***> wrote: 







Heya! Unfortunately you will have to resubmit the entire toml and resign it. The signature is made over your net address.
So go through the entire process again and sign it again (just don't change the metadata fields this time! and also use the IP:PORT form instead of a dns like you did in this pr). Thank you!

**Pull request closed without merging**
